version: "3.8"
services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345
  app:
    image: rafael/books
    ports:
      - "8080:8080"
    depends_on:
      - db
